# Configuração geral do bot
Config:
  
  # put your token bot here
  token: ""
  
  # put here your tag plugin.
  tag: "&3[H_Bot]"
  
  # put activity of bot here
  activity: "{online}/{max}"
  
  # put here guild id of your server.
  guildID: ""